input: touchscreen: Fix unused result warnings
Fixes:
../drivers/input/touchscreen/focaltech_touch/focaltech_core.c:979:3:
error: ignoring return value of function declared with
'warn_unused_result' attribute [-Werror,-Wunused-result]
                PTR_ERR(acl_desc);
                ^~~~~~~ ~~~~~~~~
../drivers/input/touchscreen/focaltech_touch/focaltech_core.c:986:3:
error: ignoring return value of function declared with
'warn_unused_result' attribute [-Werror,-Wunused-result]
                PTR_ERR(sgl_desc);
                ^~~~~~~ ~~~~~~~~

Change-Id: I941c32696a52a84a0a9272d4f969755932925aaa